pipeline:
  identifier: Build_esweeney_snyk_juice_shop_1783542013401
  name: Build juice-shop
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1783541989359
        repoName: esweeney-snyk/juice-shop
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - parallel:
                  - step:
                      type: Snyk
                      name: Snyk SCA
                      identifier: Snyk_SCA
                      spec:
                        mode: orchestration
                        config: oss
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                          fail_on_severity: high
                        privileged: true
                        auth:
                          access_token: snyk_uat.1fcad39e.eyJlIjoxNzkxMzE4MzQ0LCJoIjoic255ay5pbyIsImoiOiJBWjlEYUljUVRVYU94UC1rTVFwMHZnIiwicyI6Ii01bE5pSWdpUlE2eHdFUERleVhpR0EiLCJ0aWQiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBIn0.NX12f_NJRG5FzOcDOnk3wKBVGYwJz7jv5_RUm4VXZdm4YIGspqlrKOwAtZzaVI1_yXQtuWYX-bM65Nfm5r6SAQ
                        tool:
                          ingest_tool_severity: true
                  - step:
                      type: Snyk
                      name: Snyk SAST
                      identifier: Snyk_SAST
                      spec:
                        mode: orchestration
                        config: code
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                          fail_on_severity: high
                        privileged: true
                        auth:
                          access_token: snyk_uat.1fcad39e.eyJlIjoxNzkxMzE4MzQ0LCJoIjoic255ay5pbyIsImoiOiJBWjlEYUljUVRVYU94UC1rTVFwMHZnIiwicyI6Ii01bE5pSWdpUlE2eHdFUERleVhpR0EiLCJ0aWQiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBIn0.NX12f_NJRG5FzOcDOnk3wKBVGYwJz7jv5_RUm4VXZdm4YIGspqlrKOwAtZzaVI1_yXQtuWYX-bM65Nfm5r6SAQ
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: lint
                  name: lint
                  spec:
                    command: npm run lint
                  timeout: ""
                  type: Run
              - step:
                  identifier: e2e
                  name: e2e
                  spec:
                    command: npm run e2e
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        type: CI
